### ISSUE TITLE
Add config option for number format in excel export (decimal separator)

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/tables#185]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
It would be nice to get a config option to set the decimal separator for excel export.
At the moment it's "." (dot) and if comma is used in local settings the numbers are rendered as date in excel.

**Comment by mauthi** [comment]
Any update here? Maybe you give me a small advice where this can be done and I will try it.

**Comment by aocneanu** [comment]
@mauthi with the latest version (pushed now) we improves numbers handling.

We will deprecate money soon.

Using number instead of money will allow formatting numbers using user's locale.

the current supported attrs for the number object are:

```json
"number": {
    "precision": 2,
    "symbol": "pcs",
    "template": "%s %v"
}
```

@gandesc please update the docs.

@vmcvlad, @raftx24. @GITmanuela  fyi

**Comment by mauthi** [comment]
I just tested this - looks fine. Thx.

**Comment by mauthi** [comment]
Question: Is the same improvement for forms also done or is this replacement of money with number only done for tables?

**Comment by aocneanu** [comment]
it's only for tables, but would be a good addition for forms as well. Feel free to do a PR ;)
