### ISSUE TITLE
VueDatatable

### ISSUE THREAD

**Issue by subtain-haider** [laravel-enso/tables#196]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Does anyone have source code (front end and backend) of this datatable??
And is it included in enso or we have to make it by our own??
Note that am talking about this specific picture which includes different filtering options.

![Screenshot](https://user-images.githubusercontent.com/60756535/77840159-7c73f600-719d-11ea-95c2-2b40250884b1.png)

**Comment by aocneanu** [comment]
Read [this](https://github.com/laravel-enso/tables/issues/192#issuecomment-599679781)

**Comment by gandesc** [comment]
Hi, 

You may find the examples' source files here: [repo](https://github.com/laravel-enso/examples/tree/master/src/resources/views/table)

In the same package you'll find both back-end and front-end.

Please be aware that this example package is no longer maintained and some things might have changed since the last commit, but hopefully, it will point you in the right direction.
